theme: jekyll-theme-minimal
title: Movie wars and war movies
description: Data story website for ADA project 2022 team abracADAbra2022
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: War and movies
    url: index
  - title: First question
    url: first
  - title: Second question
    url: second
  - title: Third question 
    url: third
